"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv

load_dotenv()

from pathlib import Path
from datetime import timedelta
import os 
from dotenv import load_dotenv
from corsheaders.defaults import default_headers

# 1. .env 파일 로드
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# 2. 환경 변수에서 값 가져오기 (없으면 에러 나거나 기본값 사용)
SECRET_KEY = os.getenv('SECRET_KEY')

# DEBUG는 문자열 'True'인지 확인
DEBUG = os.getenv('DEBUG') == 'True'

# 배포 시엔 서버 IP를 여기에 넣어야 함
ALLOWED_HOSTS = ['*']

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e4o#)q7kw(x7*usbw_zjj@=lzebeytytw-bpkl-inj1gh(85hn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django_apscheduler',
    'django.contrib.staticfiles',

    # 1. 도구
    'rest_framework',            # API 도구
    'rest_framework_simplejwt',  # 1단계 이메일 로그인용 'Token' 인증
    'corsheaders',               # 'CORS' (보안 허가증) 도구

    # 2. 앱
    'users.apps.UsersConfig',    # users 앱 (CustomUser 담당)
    'core.apps.CoreConfig',      # core 앱 (Document 담당)
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# "우리 공식 User 모델을 'users' 앱의 'CustomUser'로 설정"
AUTH_USER_MODEL = 'users.CustomUser'

# "일단 개발 중이니, 모든 주소에서 오는 요청을 다 허용" (CORS)
CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),   # Access 토큰 만료 시간 (예: 1시간)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),    # Refresh 토큰 만료 시간 (예: 7일)
    
    # 'Token' 방식과 달리, 헤더에 'Bearer' 키워드를 사용합니다.
    "AUTH_HEADER_TYPES": ("Bearer",), 
}

# 파일 업로드(Media) 설정
# 웹에서 접근할 URL (예: http://localhost:8000/media/파일.jpg)
MEDIA_URL = '/media/'

# 실제 파일이 저장될 서버 내 경로 (backend/media 폴더)
MEDIA_ROOT = BASE_DIR / 'media'


# Google OAuth 설정
<<<<<<< HEAD
GOOGLE_OAUTH_CLIENT_ID = os.getenv("GOOGLE_OAUTH_CLIENT_ID")
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH_CLIENT_SECRET")
GOOGLE_OAUTH2_REDIRECT_URI = os.getenv("GOOGLE_OAUTH2_REDIRECT_URI")

# Google OAuth Scopes
GOOGLE_OAUTH2_SCOPES = [
    'openid',
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
    'https://www.googleapis.com/auth/gmail.readonly',
]

# 허용할 프론트엔드 주소 등록
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React 기본 포트
    "http://localhost:5173",  # Vite/Vue 기본 포트
    "http://127.0.0.1:3000",
]

# 쿠키/인증정보 포함 허용
CORS_ALLOW_CREDENTIALS = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app', 
    'https://*.ngrok-free.dev', 
    'http://localhost:3000',
]

# 기존 헤더에 ngrok 우회용 헤더 추가 허용
CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
]

OLLAMA_MODEL_NAME = "gemma3:4b"