# Generated by Django 5.2.7 on 2025-11-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job_template',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
    ]
