# Generated by Django 5.2.7 on 2025-11-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_job_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_neatness_score',
            field=models.FloatField(default=0.0),
        ),
    ]
