# Generated by Django 5.2.7 on 2025-11-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_last_neatness_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gmail_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
