# Generated by Django 5.2.7 on 2025-11-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_textdocument_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdocument',
            name='is_organized',
            field=models.BooleanField(default=False),
        ),
    ]
