# Generated by Django 5.2.7 on 2025-11-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_textdocument_is_organized'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdocument',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
