# Generated by Django 5.2.7 on 2025-11-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_textdocument_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdocument',
            name='file_path',
            field=models.CharField(blank=True, db_index=True, max_length=1024),
        ),
    ]
