# Generated by Django 5.2.7 on 2025-11-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_textdocument_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdocument',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
