# Generated by Django 5.2.7 on 2025-11-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_textdocument_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdocument',
            name='email_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='textdocument',
            name='sender',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
